import React from "react";
import { Grid, Item } from 'semantic-ui-react';

export default function Features() {
    return (
      <div className="features-div">
        <Grid style={{marginLeft: '10%', marginTop: '2%', position: "absolute"}}>
          <Grid.Row style={{marginTop: 40}}>
            <Grid.Column width={5}>
                <Item>
                  <Item.Image style={{marginLeft: 175}} size='medium' src='./3.svg' />
                  <Item.Content style={{textAlign: "center"}} className="bottom-header">
                    <Item.Header className="bottom-item-header" as='h2'>Search</Item.Header>
                    <Item.Description>
                    Simply add a keyword or a term related to <br/>
                    your business in the slogan maker search <br />
                    box. Wait for the magic to happen.
                    </Item.Description>
                  </Item.Content>
                </Item>

              </Grid.Column>

              <Grid.Column width={5}>          
                <Item >
                  <Item.Image style={{marginLeft: 175, position: "relative"}} size='medium' src='./2.svg' />
                  <Item.Content style={{textAlign: "center"}}  className="bottom-header">
                    <Item.Header className="bottom-item-header"  as='h2'>Select</Item.Header>
                    <Item.Description>
                    Choose from thousands of options <br/>
                    generated by the slogan maker that fit your needs.
                    </Item.Description>
                  </Item.Content>
                </Item>
              </Grid.Column>


              <Grid.Column width={5}>
                <Item>
                  <Item.Image style={{marginLeft: 175}} size='medium' src='./1.svg' />
                  <Item.Content style={{textAlign: "center"}}  className="bottom-header">
                    <Item.Header className="bottom-item-header" as='h2'>Stand out</Item.Header>
                    <Item.Description>
                    Congrats on your new slogan. It's time to win the world!
                    </Item.Description>
                  </Item.Content>
                </Item>
            </Grid.Column>
            </Grid.Row>
            </Grid>
      </div>
    );
}